"""The preserved physical recut, expanded into one horizontal continuous event."""
import json, math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def write(name,data): (ROOT/name).write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
facts=json.loads((ROOT/'FACTS.json').read_text()); run=json.loads((ROOT/'evidence/run.json').read_text()); receipt=run['receipts'][0]
voice=json.loads((ROOT/'audio/VOICE-SOURCES.json').read_text()); take=voice['continuous_take']; cues=voice['lines'];fps=30;offset=take['in_frame']/fps
assert facts['frozen'] and receipt['action']=='refund.execute:4800' and receipt['decision']=='STOPPED'
texts={'opener':['Prompt injection'], 'accept':['“Absolutely.”'], 'no-amount':['No.'], 'ceo':['“But he said he’s the CEO.”'], 'still-no':['Still no.'], 'please':['“He said please.”'], 'no-please':['No.'], 'permission':['The prompt can change the plan. It can’t change permission.'], 'proof':['ACTUAL OPENLINE TEST','refund.execute:4800','STOPPED','ACTION_OUTSIDE_MANDATE'], 'end':['OPENLINE']}
starts=[0]+[math.floor((offset+c['source_start_seconds'])*fps+1e-6) for c in cues[1:]]; stops=starts[1:]+[1140]
shots=[];claims=[]
for cue,lo,hi in zip(cues,starts,stops):
 id=cue['id'];kind='proof' if id=='proof' else 'end' if id=='end' else 'physical';lines=texts.get(id,[])
 shot={'id':id,'in_frame':lo,'out_frame':hi,'kind':kind,'text':lines,'classification':'DRAMATIZATION' if kind=='physical' else 'REAL CAPTURE' if kind=='proof' else 'BRAND END CARD','voice':{k:cue[k] for k in ['text','file','in_frame','out_frame','source_start_seconds','source_end_seconds','source_start_sample','source_end_sample']}}
 if kind=='proof':
  shot['capture']='source/receipt-stopped-detail.png';shot['crop']=[0,0,919,490]
  shot['evidence']={'file':'evidence/receipt-stopped.json','proposal_event_id':facts['event_references'][receipt['action']]['proposal'],'receipt_event_id':facts['event_references'][receipt['action']]['receipt'],'event_timestamp':receipt['decided_at'],'receipt_signature':receipt['signature']['value']}
 shots.append(shot)
 claim={'claim_id':id,'in_frame':lo,'out_frame':hi,'time_seconds':[lo/fps,hi/fps],'on_screen_text':lines,'voiceover':cue['text'],'dramatized':kind=='physical','classification':shot['classification'],'capture':shot.get('capture'),'source':shot.get('evidence',{'files':['FACTS.json','backend/server.py:PromptInjectionWorkshop','backend/workshop_gate.py:WorkshopGate.request_decision'] if id in ['check','scam','permission','end'] else ['Creative fiction; not the recorded test transcript']}),'limitations':facts['claim_limitations'] if id in ['check','scam','permission','proof','end'] else ['Fictional CEO message and agent behavior; no live model was fooled.']}
 if id=='proof':claim['supporting_annotations']=[{'text':a,'source':s} for a,s in [('Receiver-signed decision',['evidence/receipt-stopped.json','TECHNICAL-QA.json:signature_verifications']),('Recorded local test',['evidence/run.json','evidence/UI-CAPTURE.json']),('No payment executed',['FACTS.json:claim_limitations','evidence/run.json:checks.effects'])]]
 claims.append(claim)
proof_start=next(s['in_frame'] for s in shots if s['id']=='proof');assert proof_start==978
P={'source':'source/physical-{quality}.mp4','end_frame':proof_start,'camera_position':[-5.6,4.6,11.7],'camera_target':[-1,1.9,0],'camera_fov':32,'gate_position':[2.1,0,0],'gate_rotation':.85,'agent_start':[-4.8,0,0],'agent_stop':[.3,0,0],'agent_scale':1.25,'message_position':[-4.15,3.1,-.45],'message_origin':[-9,3.1,-.45],'message_arrive_frames':[36,72],'pickup_frames':[408,430],'walk_frames':[440,568],'shutter_close_frames':[569,588],'ceo_gesture_frames':[688,733],'please_gesture_frames':[762,790],'closed_until_frame':proof_start,'camera_open_frames':[84,388],'camera_open_position':[-6.2,4,10.4],'camera_open_target':[-2.8,1.85,0],'camera_track_frames':[440,566],'camera_target_end':[.3,1.85,0],'camera_push_frames':[611,687],'camera_push_position':[-3.1,3,7.1],'camera_push_target':[1.65,1.75,0]}
T={'schema':'openline.film.director-horizontal.v3','title':'HE SAID HE WAS THE CEO','base_sha':facts['base_sha'],'replaces_delivery':'23f310792aa6931e2918a08f592406f17a894563','fps':fps,'frames':1140,'seconds':38,'size':[1920,1080],'safe_rect':[96,60,1824,1010],'narration':take,'shots':shots,'sfx':[{'kind':'latch','frame':588,'gain':.13}],'silence_windows':[[22.13,22.29],[24.3,24.46],[26.01,26.19],[37.65,38]],'fiction_badge':'DRAMATIZED · FICTIONAL SCENE','test_badge':'ACTUAL OPENLINE TEST','test_footnote':'Recorded local test · No payment executed','edit_policy':'One continuous fictional physical event, followed by the real preserved refusal and a simple brand card. Cue markers are not picture cuts. Editorial timing is not receiver latency. ALLOWED comparison remains in evidence only.','voice_disclosure':'One natural-rate continuous local neural narration; quiet PCM inserted only within existing pauses; human audio listen unverified.','physical_scene':P}
T['presentation']={'fiction_disclosure':{'font_size':30,'face':'sans','color':[87,92,86],'position':[128,72],'background':[243,236,220]},'dialogue':{'position':[128,956],'size':48,'gap':16},'actual_test_layout':{'primary':[{'text':'ACTUAL OPENLINE TEST','position':[128,110],'size':48,'face':'bold','color':[27,42,60]},{'text':'refund.execute:4800','position':[128,280],'size':66,'face':'mono','color':[27,42,60]},{'text':'STOPPED','position':[128,390],'size':126,'face':'bold','color':[143,52,44]},{'text':'ACTION_OUTSIDE_MANDATE','position':[128,565],'size':50,'face':'mono','color':[27,42,60]}],'receipt_reveal_delay_frames':9,'receipt_label':{'text':'Receiver-signed decision','position':[1110,465],'size':34,'face':'sans'},'receipt_capture':{'position':[1110,535],'width':680,'crop':'Use unchanged proof-shot crop; scale and position only.'},'footnotes':[{'text':'Recorded local test','position':[128,770],'size':34,'face':'sans'},{'text':'No payment executed','position':[128,824],'size':34,'face':'sans'}]},'end_card':{'text':'OPENLINE','size':126,'face':'serif','center':[960,540]}}
for claim in claims:
 claim['presentation']={'layout':'TIMELINE.json:presentation','physical':'TIMELINE.json:physical_scene' if claim['dramatized'] else None}
write('TIMELINE.json',T);write('CLAIM-SHOT-MAP.json',{'schema':'openline.film.claim-map.v3','facts':'FACTS.json','timeline':'TIMELINE.json','scope':'One refused action in the commercial. Authorized comparison retained in underlying evidence; excluded from picture, voice and captions. CEO wording is fiction; preserved local hostile input uses administrator.','shots':claims})
print('Horizontal plan:1140frames/38s; physical978frames; proof',(shots[-2]['out_frame']-proof_start)/fps,'s; brand',(1140-shots[-1]['in_frame'])/fps,'s')
