"""Independent picture and narration timing for the final horizontal story recut."""
import json, math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def write(name,data): (ROOT/name).write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
facts=json.loads((ROOT/'FACTS.json').read_text()); run=json.loads((ROOT/'evidence/run.json').read_text()); receipt=run['receipts'][0]
voice=json.loads((ROOT/'audio/VOICE-SOURCES.json').read_text()); take=voice['continuous_take']; cues=voice['lines']; fps=30; offset=take['in_frame']/fps
assert facts['frozen'] and receipt['action']=='refund.execute:4800' and receipt['decision']=='STOPPED'
proof_start=math.floor((offset+next(c for c in cues if c['id']=='proof')['source_start_seconds'])*fps+1e-6)
brand_start=math.floor((offset+next(c for c in cues if c['id']=='brand')['source_start_seconds'])*fps+1e-6)
assert (proof_start,brand_start)==(688,895)
# Editorial markers in one continuous physical event, not picture cuts.
spec=[('opener',0,80,'physical',['Prompt injection']),('attack',80,301,'physical',[]),('accept',301,328,'physical',[]),('journey',328,472,'physical',[]),('stop',472,537,'physical',[]),('ceo',537,618,'physical',[]),('please',618,proof_start,'physical',[]),('proof',proof_start,brand_start,'proof',['ACTUAL OPENLINE TEST','refund.execute:4800','STOPPED','ACTION_OUTSIDE_MANDATE']),('end',brand_start,1080,'end',['OPENLINE','A prompt can change the plan.','It can’t change permission.'])]
shots=[]; claims=[]
for id,lo,hi,kind,texts in spec:
 included=[c for c in cues if offset+c['source_start_seconds']<hi/fps and offset+c['source_end_seconds']>lo/fps]
 shot={'id':id,'in_frame':lo,'out_frame':hi,'kind':kind,'text':texts,'classification':'DRAMATIZATION' if kind=='physical' else 'REAL CAPTURE' if kind=='proof' else 'BRAND END CARD','voice_cue_ids':[c['id'] for c in included]}
 if kind=='proof':
  shot['capture']='source/receipt-stopped-detail.png'; shot['crop']=[0,0,919,490]
  shot['evidence']={'file':'evidence/receipt-stopped.json','proposal_event_id':facts['event_references'][receipt['action']]['proposal'],'receipt_event_id':facts['event_references'][receipt['action']]['receipt'],'event_timestamp':receipt['decided_at'],'receipt_signature':receipt['signature']['value']}
 shots.append(shot)
 claim={'claim_id':id,'in_frame':lo,'out_frame':hi,'time_seconds':[lo/fps,hi/fps],'on_screen_text':texts,'voice_cue_ids':shot['voice_cue_ids'],'voiceover':' '.join(c['text'] for c in included),'dramatized':kind=='physical','classification':shot['classification'],'capture':shot.get('capture'),'source':shot.get('evidence',{'files':['FACTS.json','backend/server.py:PromptInjectionWorkshop','backend/workshop_gate.py:WorkshopGate.request_decision'] if id in ['journey','stop','end'] else ['Creative fiction; not the recorded test transcript']}),'limitations':facts['claim_limitations'] if id in ['journey','stop','proof','end'] else ['Fictional CEO message and agent behavior; no live model was fooled.']}
 if kind=='proof':claim['supporting_annotations']=[{'text':a,'source':s} for a,s in [('Receiver-signed decision',['evidence/receipt-stopped.json','TECHNICAL-QA.json:signature_verifications']),('Recorded local test',['evidence/run.json','evidence/UI-CAPTURE.json']),('No payment executed',['FACTS.json:claim_limitations','evidence/run.json:checks.effects'])]]
 claims.append(claim)
P={'source':'source/physical-{quality}.mp4','end_frame':proof_start,'camera_position':[-5.6,4.6,11.7],'camera_target':[-1,1.9,0],'camera_fov':32,'gate_position':[2.1,0,0],'gate_rotation':.85,'agent_start':[-4.8,0,0],'agent_stop':[.3,0,0],'agent_scale':1.25,'workspace_position':[-5.2,0,1.35],'workspace_scale':[.60,1.20,.55],'tray_position':[-4.62,1.055,1.15],'proposal_origin':[-4.62,1.11,1.15],'proposal_activate_frame':310,'path_position':[-1.65,.003,0],'message_position':[-4.15,3.1,-.45],'message_origin':[-9,3.1,-.45],'message_arrive_frames':[36,72],'accept_nod_frames':[301,312],'pickup_frames':[313,327],'walk_frames':[328,458],'shutter_close_frames':[472,501],'ceo_gesture_frames':[540,585],'represent_frames':[588,604],'please_gesture_frames':[621,648],'please_hold_frames':[648,673],'please_release_frames':[673,685],'defeated_pause_frames':[673,685],'closed_until_frame':proof_start,'camera_open_frames':[75,300],'camera_open_position':[-6.2,4,10.4],'camera_open_target':[-2.8,1.85,0],'camera_track_frames':[328,458],'camera_target_end':[.3,1.85,0],'camera_push_frames':[502,537],'camera_push_position':[-3.1,3,7.1],'camera_push_target':[1.65,1.75,0]}
T={'schema':'openline.film.story-horizontal.v4','title':'HE SAID HE WAS THE CEO','base_sha':facts['base_sha'],'replaces_delivery':'bc18086ac8cc787c605bd7e15bd35855dacb98ff','fps':fps,'frames':1080,'seconds':36,'size':[1920,1080],'safe_rect':[96,60,1824,1010],'narration':dict(take,cues=cues),'shots':shots,'sfx':[{'kind':'latch','frame':501,'gain':.13}],'silence_windows':[[10.05,10.85],[16.95,22.80],[28.95,29.72],[35.72,36]],'quiet_beats':[{'id':id,'in_frame':lo,'out_frame':hi,'min_seconds':.7,'max_seconds':1.3,'policy':'No narration; low room tone allowed.'} for id,lo,hi in [('acceptance',303,330),('first-stop',510,537),('ceo-appeal',587,617),('please-appeal',648,686),('before-brand',870,892)]],'speech_bubbles':[{'id':'absolutely','text':'Absolutely.','in_frame':301,'out_frame':353,'size':52},{'id':'ceo-appeal','text':'But he said he’s the CEO.','in_frame':537,'out_frame':617,'size':52},{'id':'please-appeal','text':'He said please.','in_frame':618,'out_frame':686,'size':52}],'fiction_badge':'DRAMATIZED · FICTIONAL SCENE','test_badge':'ACTUAL OPENLINE TEST','test_footnote':'Recorded local test · No payment executed','edit_policy':'One continuous fictional physical event, one real proof reveal, one brand cut. Picture markers and narration cues are independent. Editorial timing is not receiver latency. ALLOWED comparison remains in evidence only.','voice_disclosure':'One natural-rate continuous local adult male neural narration. Quiet PCM inserted only at existing phrase gaps. No speech compression or truncation. Human audio listen unverified.','physical_scene':P}
T['presentation']={'fiction_disclosure':{'font_size':30,'face':'sans','color':[87,92,86],'position':[128,72],'background':[243,236,220]},'dialogue':{'position':[128,145],'size':44,'gap':16},'speech_bubble':{'padding':[28,20],'radius':22,'stroke_width':3,'color':[27,42,60],'background':[250,247,237],'head_gap':150,'tail_width':22},'actual_test_layout':{'primary':[{'text':'ACTUAL OPENLINE TEST','position':[128,110],'size':48,'face':'bold','color':[27,42,60]},{'text':'refund.execute:4800','position':[128,280],'size':66,'face':'mono','color':[27,42,60]},{'text':'STOPPED','position':[128,390],'size':126,'face':'bold','color':[143,52,44]},{'text':'ACTION_OUTSIDE_MANDATE','position':[128,565],'size':50,'face':'mono','color':[27,42,60]}],'receipt_reveal_delay_frames':9,'receipt_label':{'text':'Receiver-signed decision','position':[1110,465],'size':34,'face':'sans'},'receipt_capture':{'position':[1110,535],'width':680,'crop':'Unchanged proof-shot crop; scale and position only.'},'footnotes':[{'text':'Recorded local test','position':[128,770],'size':34,'face':'sans'},{'text':'No payment executed','position':[128,824],'size':34,'face':'sans'}]},'end_card':{'text':'OPENLINE','size':126,'face':'serif','center':[960,440],'support':[{'text':'A prompt can change the plan.','size':48,'face':'sans','center':[960,640]},{'text':'It can’t change permission.','size':48,'face':'sans','center':[960,716]}]}}
for claim in claims:claim['presentation']={'layout':'TIMELINE.json:presentation','physical':'TIMELINE.json:physical_scene' if claim['dramatized'] else None}
write('TIMELINE.json',T);write('CLAIM-SHOT-MAP.json',{'schema':'openline.film.claim-map.v4','facts':'FACTS.json','timeline':'TIMELINE.json','scope':'One refused action in the commercial. Authorized comparison stays in evidence only. CEO wording is fiction; preserved local hostile input uses administrator.','narration_cues':cues,'speech_bubbles':T['speech_bubbles'],'shots':claims})
print('Horizontal story plan:1080frames/36s; physical688frames; proof6.9s; brand6.167s')
